[book]
title = "Backend interview"
description = "Книжка для подготовки к собеседованию на должность backend developer"
language = "ru"


[output.html]
mathjax-support = true
site-url = "/book/"
git-repository-url = ""
